services:
  api:
    container_name: ahorroland-backend
    image: sergioizqdev/ahorroland-backend:${API_VERSION:-latest} 
    restart: unless-stopped
    ports:
      - "5001:5000"  # Mapear al puerto 5000 que usa la app
    networks:
      - ahorroland-red
    depends_on:
      - db
    environment:
      # Aplicaci√≥n
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      
      # Base de Datos
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Database=${DB_DATABASE};Uid=${DB_USER};Pwd=${DB_PASSWORD};AllowUserVariables=true;SslMode=Preferred;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionLifetime=180;ConnectionReset=true;ConnectionTimeout=30
      
      # Email
      - EmailSettings__SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailSettings__SmtpUser=${EMAIL_SMTP_USER}
      - EmailSettings__SmtpPass=${EMAIL_SMTP_PASS}
      - EmailSettings__SmtpPort=${EMAIL_SMTP_PORT}
      - EmailSettings__EnableSsl=${EMAIL_ENABLE_SSL}

  frontend:
    container_name: ahorroland-frontend
    image: sergioizqdev/ahorroland-frontend:${FRONTEND_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3001:80"  # Cambiado de 8080 a 3001 (puerto libre)
    networks:
      - ahorroland-red