services:
  api:
    container_name: ahorroland-backend
    image: sergioizqdev/ahorroland-backend:${API_VERSION:-latest} 
    restart: unless-stopped
    ports:
      - "5001:80"  # Cambiado de 80 a 5001 (puerto libre)
    networks:
      - ahorroland-red
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    container_name: ahorroland-frontend
    image: sergioizqdev/ahorroland-frontend:${FRONTEND_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3001:80"  # Cambiado de 8080 a 3001 (puerto libre)
    networks:
      - ahorroland-red